class Lists
  attr_reader :categories, :regions

  def initialize
    @categories = [
      'Automotive',
      'Business, Admin & Writing',
      'Deliveries & Removals',
      'Design & Photography',
      'Education & Training',
      'Hair & Beauty',
      'Home & Gardening',
      'IT & Software Development'
    ]
    @regions = [
      'ACT - Canberra',
      'ACT - Regional',
      'NSW - Blue Mountains',
      'NSW - Central Coast',
      'NSW - Central Tablelands',
      'NSW - Central West',
      'NSW - Greater Western Sydney',
      'NSW - Far South Coast',
      'NSW - Far West',
      'NSW - Hunter Region (Newcastle)',
      'NSW - Illawarra (Wollongong)',
      'NSW - Lord Howe Island',
      'NSW - New England (north-west)',
      'NSW - Murray',
      'NSW - Mid North Coast',
      'NSW - North West Slopes',
      'NSW - Northern Rivers',
      'NSW - Northern Tablelands',
      'NSW - Orana',
      'NSW - Riverina',
      'NSW - Sapphire Coast',
      'NSW - Snowy Mountains',
      'NSW - South Coast',
      'NSW - Southern Highlands',
      'NSW - Southern Tablelands',
      'NSW - South West Slopes',
      'NSW - Sunraysia',
      'NSW - Sydney',
      'NT  - Arnhem Land',
      'NT  - Barkly Tableland',
      'NT  - Central Australia/Alice Springs',
      'NT  - Darwin Region',
      'NT  - Katherine Region',
      'NT  - Top End',
      'NT  - Victoria River',
      'QLD - Channel Country',
      'QLD - Capricorn Coast',
      'QLD - Granite Belt',
      'QLD - Maranoa',
      'QLD - Torres Strait Islands',
      'QLD - Gulf Country',
      'QLD - Whitsunday',
      'QLD - Townsville',
      'QLD - Brisbane',
      'QLD - Gold Coast',
      'QLD - Sunshine Coast',
      'QLD - West Moreton',
      'QLD - Wide Bay-Burnett',
      'QLD - South Burnett',
      'QLD - Central West Queensland',
      'QLD - South West Queensland',
      'SA  - Adelaide Plains',
      'SA  - Adelaide Hills/Mount Lofty Ranges',
      'SA  - Barossa Valley',
      'SA  - Eyre Peninsula',
      'SA  - Far North',
      'SA  - Fleurieu Peninsula',
      'SA  - Flinders Ranges',
      'SA  - Kangaroo Island',
      'SA  - Limestone Coast',
      'SA  - Mid North',
      'SA  - Clare Valley',
      'SA  - Murray Mallee',
      'SA  - Murraylands',
      'SA  - Riverland',
      'SA  - Yorke Peninsula',
      'SA  - Copper Triangle',
      'TAS - Central Highlands',
      'TAS - Midlands',
      'TAS - West Coast',
      'TAS - Hobart',
      'VIC - Barwon South West',
      'VIC - Gippsland',
      'VIC - Grampians',
      'VIC - Greater Melbourne',
      'VIC - Hume',
      'VIC - Loddon Mallee'
    ]
  end
end
